# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df194540f002e0ede545c37578f795fc583314df98abd77940dd4f4bb2f63610d367e637aa5670c8b95f9d478f0f97e3e86350286c544a890095064d269f97cf

test:
  secret_key_base: 7cd5fa9be43aaa8b87f10c3fc07fc2bf1a413d82f92e2808b304d7a2d1f212a671153399031f284a7d5c24fc2548035ae5d3d2df56f73eb08ef35d9b9bad2d4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
